AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple Go Lambda function
Resources:
  MyGoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      CodeUri: s3://local-lambdas/35a990f301f304146ff4b04bb1320374
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 10
    Metadata:
      SamResourceId: MyGoFunction
