AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AuthCPF:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      Handler: app.handler
      CodeUri: src/
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /auth
            Method: POST
