name: CI - AWS Lambda (Go)

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run Unit Tests
        run: go test -v ./...
