AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for Auth0 authentication via API Gateway

Globals:
  Function:
    Timeout: 5
    Runtime: provided.al2
    Architectures:
      - arm64
    MemorySize: 128
    Environment:
      Variables:
        AUTH0_DOMAIN: fiap-tech-challenge.us.auth0.com
        AUTH0_AUDIENCE: https://fiap-tech-challenge.us.auth0.com/api/v2/
        AUTH0_CLIENT_ID: qum1LjLVtqDQV5VlcQzR2y36TGGq0PNV
        AUTH0_CLIENT_SECRET: Qcjz_Nf74YjZxkujZfZNAHpjIjwTblZUHJKayX94hgFNkLWVqY8oMCZ8Y_UZIzOM

Resources:
  AuthApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AuthApi
      StageName: Prod
      EndpointConfiguration: REGIONAL

  AuthUser:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AuthUser
      Handler: bootstrap
      CodeUri: .
      Events:
        Login:
          Type: Api
          Properties:
            RestApiId: !Ref AuthApi
            Path: /auth/login
            Method: POST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value:
      Fn::Sub: "https://${AuthApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/auth/login"

  LambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AuthUser.Arn
