name: Build and Deploy Lambda

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker Image for Lambda
        run: docker build -t lambda-builder .

      - name: Build Lambda Binary from Docker Container
        run: |
          docker run --name temp-container lambda-builder
          docker cp temp-container:/app/bootstrap ./bootstrap
          docker rm temp-container

      - name: Package Lambda with SAM
        run: sam package --output-template-file packaged.yaml --s3-bucket your-s3-bucket

      - name: Deploy Lambda with SAM
        run: sam deploy --template-file packaged.yaml --stack-name auth --capabilities CAPABILITY_IAM
