name: Deploy Lambda via SAM

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch a ser deployada'
        required: true
        default: 'main'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar SAM CLI
        run: |
          curl -Lo sam.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip sam.zip -d sam-installation
          sudo ./sam-installation/install --update

      - name: Build da Lambda (SAM Build)
        run: sam build --use-container

      - name: Package da Lambda (SAM Package)
        run: |
          sam package \
            --template-file .aws-sam/build/template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ secrets.SAM_S3_BUCKET }}
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Deploy da Lambda (SAM Deploy)
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name auth-lambda \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Aguardar Função Lambda Ativar
        run: |
          echo "Aguardando a função Lambda atingir o estado 'Active'..."
          for i in {1..30}; do
            status=$(aws lambda get-function --function-name AuthCPF --region us-east-1 --query 'Configuration.State' --output text)
            echo "Estado atual: $status"
            if [ "$status" = "Active" ]; then
              echo "Função ativa!"
              exit 0
            fi
            sleep 10
          done
          echo "Timeout: A função Lambda não atingiu o estado Active."
          exit 1
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Publicar Versão da Lambda
        run: aws lambda publish-version --function-name AuthCPF --region us-east-1
        env:
          AWS_DEFAULT_REGION: us-east-1

      - name: Verificar Status da Stack CloudFormation
        run: aws cloudformation describe-stacks --stack-name auth-lambda --query "Stacks[0].StackStatus" --output text
        env:
          AWS_DEFAULT_REGION: us-east-1
